title: "LLM Grader"
description: "Lightweight LLM tool for autograding"
remote_theme: just-the-docs/just-the-docs
baseurl: "/llmgrader" # Only needed if using a project page
url: "https://sdrangan.github.io"

# Navigation settings
nav_sort: case_insensitive
search_enabled: true

# Markdown options
markdown: kramdown
kramdown:
  input: GFM

# Optional: GitHub repo link
github_repo_url: "https://github.com/sdrangan/llmgrader"

just_the_docs:
  favicon: "/assets/images/favicon.png"
  color_scheme: light




